server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: fraudgraph-ingestion
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

fraudgraph:
  kafka:
    raw-topic: ${TRANSACTIONS_RAW_TOPIC:transactions.raw}
    alert-topic: ${FRAUD_ALERTS_TOPIC:fraud.alerts}
